version: "2.1"
services:

  example-consumer:
    extends:
      file: docker-compose-base.yml
      service: example-consumer-base
    networks:
      - aether
    volumes:
      - ./app/logs:/code/logs

networks:
  aether:
    external:
      name: aether_internal
