version: "2.1"
services:
  example-consumer-base:
    build: ./example
    stdin_open: true
    tty: true
    environment:
     - PYTHONUNBUFFERED=1
     - KAFKA_CONFIG=/code/conf/consumer/kafka.json
     - CONSUMER_CONFIG=/code/conf/consumer/consumer.json
    volumes:
     - ./example/conf:/code/conf
    command: start
